# The backend server address to connect to
host: "http://localhost:8080/"

# The current locale
current-locale: "English"

# List of supported locales
supported-locales:
  - name: "English"
    code: "en"
  - name: "Nederlands"
    code: "nl"
  - name: "Romanian"
    code: "ro"

# The invite codes of the past events
past-codes: []